Yoast/PHPUnit-Polyfills

.phpcs.xml.dist, composer.json
This library supports PHP >= 5.5, but the default `testVersion` as set in YoastCS is `5.6-`.
Overruling the `testVersion` from within a custom ruleset is currently not possible. This is a known issue in PHPCS itself and a fix is expected to be included with PHPCS 4.x.
In the mean time, as a work-around, the `testVersion` can be overruled from the command-line.
=> CI/QA: fix testVersion for PHPCompatibility

phpunitpolyfills-autoload.php
... to prevent using a reserved keyword as a parameter name.
While this isn't forbidden, in PHP 8.0+ with named parameters this can lead to very confusing code, so better to use another name.
=> CS/QA: rename a function parameter

README.md
... with alternatives which can be used to replace that functionality.
=> README: add FAQ section covering functionality removed from PHPUnit

src/TestCases/XTestCase.php, tests/TestCases/XTestCaseTest.php
This aligns the visibility of the methods in the `XTestCase` class with the minimum acceptable visibility to allow the methods to work.
This also ensures that the visibility used in the class now matches that of the code sample in the README.
| Native method name     | Annotation     | Minimum visibility |
|------------------------|----------------|--------------------|
| `setUpBeforeClass()`   | `@beforeClass` | `public`           |
| `setUp()`              | `@before`      | `protected`        |
| `tearDown()`           | `@after`       | `protected`        |
| `tearDownAfterClass()` | `@afterClass`  | `public`           |
Fixes #10
=> XTestCase: set to lowest possible visibility

tests/TestCases/TestCaseTestTrait.php
* Commit 057a83d34ab2b27f0b80f6f54d817590db75f7b4 added the `AssertNumericType` trait and a corresponding availability test to the `TestCaseTestTrait`, but the test name did not follow the naming convention used in the file.
* Commit b5372989715ad406358e6924ded0a6e98b3e8014 added the `ExpectException` trait, but did not add a corresponding availability test to the `TestCaseTestTrait`.
* Commit 347c76864e41cf254303fc1cca9f74bb2d41ec5c added the `AssertFileDirectory` trait, but did not add a corresponding availability test to the `TestCaseTestTrait`.
Fixed now.
=> TestCaseTestTrait: add missing tests

phpunit.xml.dist, phpunitpolyfills-autoload.php, tests/Polyfills/ExpectExceptionTest.php, tests/TestListeners/TestListenerTest.php, tests/bootstrap.php
The main reason to add a test bootstrap file is to allow for defining some `class_alias`-es for PHPUnit native classes which are only used in the test suite.
This allows for some minor simplifications to the existing test code and for these same simplifications to be available for future test adjustments (which are needed for PHPUnit 10.0 support).
The XML configuration allows for only one bootstrap file, so adding a `bootstrap` file now means that the Composer `vendor/autoload.php` file has to be loaded from within the `tests/bootstrap.php` file.
This presents a problem when running the tests via a PHPUnit Phar file as the loading of the Composer autoload will block the tests from running if the PHP version used to run the Phar file is not the same PHP version as the one used to run …
=> Tests: add bootstrap file

.github/workflows/test.yml
This build is - for now - allowed to fail while support for PHPUnit 10.0 is being added to the repo.
=> CI/QA: add experimental build against PHPUnit 10.0 (unreleased)

tests/Polyfills/AssertFileDirectoryTest.php
Selectively skip some tests from the `AssertFileDirectoryTest` class.
These tests test that a method which was available between PHPUnit 5.6.0 - 9.x is polyfilled correctly for PHPUnit < 5.6.0.
As these methods have been removed in PHPUnit 10.0.0 in favour of assertions with better names, these tests will fail on PHPUnit 10.0.0.
This is not an issue, as the methods with the new names have also been polyfilled and those tests _do_ pass on PHPUnit 10.0.0.
So if people want their tests to be able to run on PHPUnit 10.0.0, they should use the new names of the methods and all will be good.
This is already [documented as such in the README](https://github.com/Yoast/PHPUnit-Polyfills#use-with-phpunit--570).
This affects the following methods:
| Old name                     | New name …
=> AssertFileDirectoryTest: allow for running the tests on PHPUnit 10.0.0

tests/TestListeners/TestListenerTest.php
The `$name` parameter for the `TestCase::__construct()` method has become mandatory and should contain the name of the test method to run.
Ref: https://github.com/sebastianbergmann/phpunit/commit/705874f1b867fd99865e43cb5eaea4e6d141582f
---
This PHPUnit 10.0.0 change will generally speaking not affect "normal" users as it is rare for them to declare `__construct()` methods in test classes or to instantiate test classes directly, as this is the responsibility of PHPUnit.
In most cases, only test code testing for cross-version PHPUnit compatibility while using PHPUnit to run the tests will be affected.
Even so, fixing this is straight-forward, as the `$name` parameter was already an optional parameter since way back when, so passing the parameter in allows the tests to run (and pass) …
=> TestListenerTest: fix PHPUnit 10.0.0 compatibility

tests/Polyfills/ExpectExceptionTest.php
... by always passing a TestResult object to the `run()` method.
The `$testResult` parameter was previously optional, but will become required as of PHPUnit 10.0.0.
Also, the `run()` method used to return an instance of `TestResult`, but will now return `void`.
Ref: sebastianbergmann/phpunit@77e6015
---
Along the same lines as 25, this PHPUnit 10.0.0 change will generally speaking not affect "normal" users.
In most cases, only test code testing for cross-version PHPUnit compatibility while using PHPUnit to run the tests will be affected.
Even so, fixing this is straight-forward, as the `$result` parameter was already an optional parameter since way back when, so instantiating the `TestResult` and passing the parameter in allows the tests to run cross-version.
The …
=> ExpectExceptionTest: fix PHPUnit 10.0.0 compatibility

src/Polyfills/AssertStringContains.php, tests/Polyfills/AssertStringContainsTest.php
PHPUnit 6.4.2 added a fix to gracefully handle the case when an empty string was passed to `assertStringContainsString()` and variant assertions. Versions earlier than that gave a "mb_strpos(): Empty delimiter" error instead.
This change adds a fix to also handle that case, when using PHPUnit-Polyfills with versions of PHPUnit earlier than 6.4.2, and passing an empty needle string.
The use of asserting true is true stops the test from being marked as risky, which is what would happen if we just `return true;`. **This is hacky, and there may be a better way for this.**
Fixes #17.
=> Handle strings containing empty strings assertions

README.md
Add version agnostic links to the PHPUnit native documentation for the assertions and exception methods polyfilled as well as miscellanous other links to the documentation.
=> README: add links to the PHPUnit documentation

src/Helpers/ResourceHelper.php
For optimal compatibility with cross-version PHP, `TypeError`s should be caught before `Exception`s.
=> ResourceHelper: minor PHP cross-version compatibility fix

tests/Polyfills/AssertClosedResourceNotResourceTest.php
Add an extra test to document the behaviour of the `shouldClosedResourceAssertionBeSkipped()` method when a non-resource is passed.
=> AssertClosedResource/ResourceHelper: add extra test

.github/workflows/test.yml
With the matrix now expanded, linting would now be done multiple times per PHP version, which isn't really necessary.
=> GH Actions: no need to lint twice

.github/workflows/test.yml, .phpcs.xml.dist, composer.json, phpunitpolyfills-autoload.php, src/Exceptions/Error.php, src/Exceptions/TypeError.php
Some of the existing code already references these classes and while not (currently) done in a PHP cross-version problematic way, it is still better to make sure these classes exist for optimal PHP cross-version compatibility.
While not strictly correct/PSR4-compliant, I've elected to put these classes in the `Exceptions` subfolder, even though these are non-namespaced classes and not strictly part of the _PHPUnit_ polyfills.
Note: the autoloader will only be called if these classes do not exist in PHP itself (PHP < 7.0), so the way it is set up now, these files will never get loaded on PHP >= 7.0 (which would otherwise cause a "Class already declared" error).
Includes:
* Explicitly excluding the PHPCompatibility notices about these classes in the PHPCS ruleset.
_Note: due to the use of …
=> Add polyfills for the PHP 7.0 `TypeError` and `Error` classes

.phpcs.xml.dist, src/Polyfills/AssertIsType.php
When adding the `TypeError`/`Error` polyfill (#36), I suddenly realized that the use of the `PHPCompatibilityWP` ruleset by the `Yoast` standard was causing certain issues not to show up, while - for this repo - they **_should_** be shown.
By setting the `severity` of all the sniffs in the `PHPCompatibilility` ruleset back to `5`, the `exclude`s from the `PHPCompatibilityWP` ruleset are effectively "undone" and we are back to using `PHPCompatibility` proper.
=> PHPCS: use PHPCompatibility proper, not PHPCompatibilityWP

.phpcs.xml.dist, README.md, composer.json, phpunitpolyfills-autoload.php, src/Exceptions/InvalidComparisonMethodException.php, src/Polyfills/AssertObjectEquals.php, src/Polyfills/AssertObjectEquals_Empty.php, src/TestCases/TestCasePHPUnitGte8.php, src/TestCases/TestCasePHPUnitLte7.php, src/TestCases/XTestCase.php, tests/Polyfills/AssertObjectEqualsPHPUnitLt940Test.php, tests/Polyfills/AssertObjectEqualsTest.php, tests/Polyfills/Fixtures/ChildValueObject.php, tests/Polyfills/Fixtures/ValueObject.php, tests/Polyfills/Fixtures/ValueObjectNoReturnType.php, tests/Polyfills/Fixtures/ValueObjectUnion.php, tests/Polyfills/Fixtures/ValueObjectUnionNoReturnType.php, tests/TestCases/TestCaseTestTrait.php
PHPUnit 9.4.0 introduced the new `Assert::assertObjectEquals()` method.
This commit:
* Adds two traits with the same name.
One to polyfill the method when not available in PHPUnit.
The other to allow for `use`-ing the trait in PHPUnit versions in which the method is already natively available.
* Adds an `InvalidComparisonMethodException` exception class.
_PHPUnit natively throws a range of different exceptions._
_The polyfill included in this library throws one exception type - the `InvalidComparisonMethodException` - with a range of different messages._
* Adds tests.
As the polyfill contains logic to match the PHPUnit native implementation as closely as possible, while still being …
=> AssertObjectEquals trait: polyfill the Assert::assertObjectEquals() method

phpunitpolyfills-autoload.php
The path building doesn't really need to use `DIRECTORY_SEPARATOR` as Windows will handle paths with forward slashes correctly anyhow.
=> Autoloader: minor simplification

README.md, phpunitpolyfills-autoload.php
Includes adding an FAQ block to the README about how to use the constant.
Fixes #46
=> Autoload: add version number constant

CHANGELOG.md
Includes fixing up a grammar error in the notes for the  previous release.
=> Changelog for the 1.0.1 release

.github/RELEASE-CHECKLIST.md, .github/workflows/test.yml, CHANGELOG.md, README.md, phpunitpolyfills-autoload.php
=> Release version 1.0.1

.github/workflows/test.yml
When a `job` has builds which are allowed to `continue-on-error` and only those fail/error, the workflow will be marked as "passed" (green), but for any PR containing builds which failed, even though they are allowed to fail, the PR will still show an :x:.
This is confusing and discouraging for people.
Currently, there are two builds which are "allowed to fail":
* A build against PHP 8.1.
* A build against PHPUnit 10.
As people are starting to test against PHP 8.1, if that build would start to fail, it needs to be looked at straight away.
However, as PHPUnit 10.0 is still under heavy development and a release is still a while away, let's not let PRs be marked as failed, when that is the only build which is failing.
=> GH Actions: selectively don't mark PRs as failed

README.md
Improve the code sample.
As of version 2.15.0 of the `shivammathur/setup-php` action for GitHub Actions, the PHPUnit Polyfills can be installed directly from this action using the `tools` key.
In that case, both this package as well as PHPUnit will be globally installed via Composer.
This commit adds an FAQ section to the readme with a little more information about how this works and how to get things running when installed like that.
=> README: various small updates / add FAQ about setup-php

composer.json
Most notably, PHP Parallel Lint 1.3.1 has improved compatibility with PHP 8.1.
Refs:
* https://github.com/php-parallel-lint/PHP-Parallel-Lint/releases/tag/v1.3.1
=> Composer: update dev dependency

phpunitpolyfills-autoload.php
The version check in the `Autoload::loadTestCase()` method could get confused if the package using this library, or a dependency of the package using this library would alias the `PHPUnit_Runner_Version`/`PHPUnit\Runner\Version` class.
As both classes contain the method we need to retrieve the version number, let's always base the loading on the available PHPUnit version number instead of the availability of either class.
=> Autoload: improve/stabilize version check for TestCase

.github/workflows/test.yml, .phpcs.xml.dist, CHANGELOG.md, README.md, composer.json, phpunit.xml.dist, phpunitpolyfills-autoload.php
=> Release version 1.0.2

.github/workflows/cs.yml, .github/workflows/lint.yml, .github/workflows/test.yml, README.md
Execute linting in a separate workflow from running the tests.
* `E_ALL` does not really contain **ALL** PHP notices across all PHP versions, in some `E_STRICT`, for instance, is excluded from `E_ALL`, so using `-1` is the better choice as that will always contain everything.
* While assertions are (as far as I'm aware) not currently used in the code base, it's still a good idea to enable `zend_assertions` in case something would be changed in the test tooling used.
This is one of the other ini settings which is not turned on by default in the `setup-php` action.
Ref: https://www.php.net/manual/en/ini.core.php#ini.zend.assertions
In Travis, when the same branch was pushed again and the "Auto cancellation" option on the "Settings" page had been turned on (as it was for most repos), any …
=> GH Actions: various improvements

tests/TestListeners/Fixtures/FailurePHPUnitGte7.php, tests/TestListeners/Fixtures/IncompletePHPUnitGte7.php, tests/TestListeners/Fixtures/RiskyPHPUnitGte7.php, tests/TestListeners/Fixtures/SkippedPHPUnitGte7.php, tests/TestListeners/Fixtures/SuccessPHPUnitGte7.php, tests/TestListeners/Fixtures/TestErrorPHPUnitGte7.php, tests/TestListeners/Fixtures/WarningPHPUnitGte7.php, tests/TestListeners/TestListenerTest.php
Initial tweaks to make the tests compatible with PHPUnit 10.x, which enforces a `mixed` return type for the `TestCase::runTest()` method.
To test the TestListener, prior to PHPUnit 7.0, overloading the `runTest()` method works best, but as of PHPUnit 10.0, the `runTest()` method has a `mixed` return type declaration (PHP 8.0+).
However, since PHPUnit 7.0, testing the TestListener also works when the test name with which the `TestCase` is instantiated is not `runTest()`.
So either way, the fixtures used for the TestListener tests need to be duplicated and have two variations.
Now the choice was which option to choose:
* Duplicate the classes and add a return type to the `runTest()` method.
* Duplicate the classes and rename the test method.
I investigated both options and have decided to …
=> Tests: tweaks for PHPUnit 10.x compatibility

src/Polyfills/AssertClosedResource.php, tests/Polyfills/AssertClosedResourceTestCase.php
The `sebastian/exporter` package has been a dependency of PHPUnit from before PHPUnit 4.8.x (minimum supported version by this library), so it is safe to use the same variable export methodology as PHPUnit itself uses.
The class is prefixed via PHP_Scoper when it is includes as part of a PHPUnit Phar file and the toggle added will make sure the class can be loaded both when run via a Composer install, as well as when run via a Phar file.
Also note that the Exporter reports closed resources as `NULL`. This has been reported upstream via https://github.com/sebastianbergmann/exporter/issues/36 and for the polyfill a fix has been put in place to work around this.
Props to @schlessera for the feedback leading to this improvement.
**Important**:
While the `sebastian/exporter` package has, in …
=> AssertClosedResource: improve error messages

tests/bootstrap.php
This constant signals to PHPUnit that the tests themselves may run other tests and will prevent tests on older PHPUnit versions from being marked as "risky" for "closing more than just their own buffers".
=> Test bootstrap: declare the `PHPUNIT_TESTSUITE` constant

tests/Helpers/Fixtures/ClassWithProperties.php
Dynamic (non-explicitly declared) property usage is expected to be deprecated as of PHP 8.2 and will become a fatal error in PHP 9.0.
There are a number of ways to mitigate this:
* If it's an accidental typo for a declared property: fix the typo.
* For known properties: declare them on the class.
* For unknown properties: add the magic `__get()`, `__set()` et al methods to the class or let the class extend `stdClass` which has highly optimized versions of these magic methods build in.
* For unknown _use of_ dynamic properties, the `#[AllowDynamicProperties]` attribute can be added to the class. The attribute will automatically be inherited by child classes.
In this case, the test is intentionally setting a dynamic property, so using the attribute is the best way to safeguard the handling …
=> PHP 8.2: allow dynamic property on test fixture

.github/workflows/cs.yml, .github/workflows/lint.yml, .github/workflows/test.yml
The action used to install Composer packages and handle the caching has released a new major (and some follow-up patch releases), which means, the action reference needs to be updated to benefit from it.
Includes adding `--no-interaction` to "plain" Composer commands to potentially prevent CI hanging if, for whatever reason, interaction would be needed in the future.
Refs:
* https://github.com/ramsey/composer-install/releases/tag/2.0.0
* https://github.com/ramsey/composer-install/releases/tag/2.0.1
* https://github.com/ramsey/composer-install/releases/tag/2.0.2
=> GH Actions: version update for `ramsey/composer-install`

.github/workflows/cs.yml, .github/workflows/lint.yml, .github/workflows/test.yml
A number of predefined actions have had major release, which warrant an update the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/checkout/releases
=> GH Actions: version update for various predefined actions

.github/workflows/test.yml
The minimum PHP requirement for PHPUnit 10 has been changed to PHP 8.1.
Ref: https://github.com/sebastianbergmann/phpunit/commit/95b61586c5d9b90bcaa516ddca0af00efc408940
=> GH Actions/test: PHPUnit 10 needs PHP 8.1

CHANGELOG.md, README.md, phpunitpolyfills-autoload.php
Includes minor tweaks to the README to clear up some confusion.
=> Changelog for release 1.0.4

.github/workflows/cs.yml, .github/workflows/lint.yml, .github/workflows/test.yml
... of the bash `date` command in the earlier pulled cache busting.
All the repos in the Yoast organisation contain a `<arg name="cache" value="./.cache/phpcs.cache"/>` directive in the PHPCS ruleset.
This directive makes running PHPCS faster by caching the run results in a file and only scanning changed files when running PHPCS again.
However, when there is no cache available, running with the `cache` option enabled will make PHPCS _slower_ as the cache needs to be created and the file read/write actions slow PHPCS down.
In GH Actions, we are not caching the PHPCS `cache` file, which means that there is cache file available and running with `cache` will be slower.
By adding the `--no-cache` option, the `cache` directive in the ruleset is ignored, which should result in a slightly faster …
=> GH Actions: various tweaks

tests/Polyfills/AssertClosedResourceNotResourceTest.php, tests/Polyfills/AssertStringContainsTest.php, tests/TestCases/TestCaseTestTrait.php
As of PHPUnit 10, data providers are (again) expected to be `static` methods.
This updates the test suite for the polyfills to respect that.
=> Tests: make dataproviders `static`

tests/Polyfills/AssertClosedResourceNotResourceTest.php, tests/Polyfills/AssertClosedResourceTestCase.php
... for a minor change in the exception message thrown by PHPUnit 10.0.
... for a minor change in the exception message thrown by PHPUnit 10.0.
=> AssertClosedResource* Tests: update exception message expectation

README.md
As PHPUnit 10.0 has been released, the `main` branch of the PHPUnit docs now points to the PHPUnit 10.0 documentation, while the last release of the Polyfills supports PHPUnit 4.x - 9.x.
This commit updates the links in the README to point explicitly to the PHPUnit 9.6 documentation.
PHPUnit 10.0 support will be handled in a new major of the Polyfills and the links should be updated (again) to point to the PHPUnit 10.0 documentation in the branch containing that major.
=> README: update links to PHPUnit docs

src/Polyfills/AssertClosedResource.php, src/Polyfills/AssertFileDirectory.php, src/Polyfills/AssertStringContains.php, tests/Polyfills/AssertClosedResourceNotResourceTest.php, tests/Polyfills/AssertFileDirectoryTest.php, tests/Polyfills/AssertStringContainsTest.php
The assertions in the `AssertClosedResource` trait generate a specific error message.
However, if a custom `$message` parameter was passed, that message would not be displayed and only the custom `$message` would be shown when the assertion failed.
As the PHPUnit native error message from the _underlying_ assertion used - _"true is not false"_ - would be obscuring the real issue, this commit adjusts the code to always display the assertion specific error message as well.
Includes tests safeguarding the fix.
Some of the assertions in the `AssertFileDirectory` trait generate a specific error message.
However, if a custom `$message` parameter was passed, that message would not be displayed and only the custom `$message` would be shown when the assertion failed.
As the PHPUnit native error …
=> Polyfills: improve handling of custom error message

.github/RELEASE-CHECKLIST.md, README.md, composer.json
The `develop` branch has been renamed to `1.x` and a new `2.x` branch will be added to hold development for the `2.x` version.
The `main` branch, from now on, will be used as the release branch for PHPUnit Polyfills 2.x.
The README for the 2.x version will be updated to reflect the features supported in the 2.x series.
This commit adds a section to the README for the 1.x branch to inform people about which versions of PHPUnit will be supported by which versions of the PHPUnit Polyfills.
=> Docs: updates for branch rename and adding of 2.x branch

phpunitpolyfills-autoload.php, src/Polyfills/AssertClosedResource.php, src/Polyfills/ExpectPHPException.php, tests/Helpers/AssertAttributesHelperTest.php, tests/Polyfills/AssertClosedResourceNotResourceTest.php, tests/Polyfills/AssertClosedResourceTestCase.php, tests/Polyfills/AssertObjectEqualsPHPUnitLt940Test.php, tests/Polyfills/AssertObjectEqualsTest.php, tests/Polyfills/AssertStringContainsTest.php, tests/Polyfills/ExpectExceptionMessageMatchesTest.php, tests/TestCases/TestCaseTestTrait.php
... which is available since PHP 5.5 and can be used now support for PHP < 5.6 has been dropped.
=> Modernize: use class resolution

src/Helpers/AssertAttributeHelper.php, src/Polyfills/AssertEqualsSpecializations.php, src/Polyfills/AssertFileEqualsSpecializations.php, src/Polyfills/AssertIsType.php, src/Polyfills/AssertObjectEquals.php, src/Polyfills/AssertStringContains.php, src/Polyfills/AssertionRenames.php, src/Polyfills/EqualToSpecializations.php, src/Polyfills/ExpectExceptionMessageMatches.php, src/Polyfills/ExpectExceptionObject.php, src/Polyfills/ExpectPHPException.php, tests/TestCases/TestCaseTestTrait.php
PHPUnit 10.0 makes all assertion and exception methods `final`, so the PHPUnit Polyfills should follow suit.
There is one trait which I've exempted from this: `AssertClosedResource`, as when the methods in that trait (and the empty version of that trait) are made `final`, we'll run into trouble on PHPUnit < 9.x.
---
Note to self: [PHPCSExtra](https://github.com/PHPCSStandards/PHPCSExtra) 1.1.0 is expected to include a sniff which can enforce this. Once that release is available, that sniff should be added to the PHPCS ruleset to safeguard this.
=> PHPUnit 10 | Make all assertion/exception methods `final`

composer.json
This can (should) be sorted out via a local dev `phpunit.xml` overload file, not via a Composer script.
=> Composer: remove `coverage-local` script

README.md, phpunitpolyfills-autoload.php, src/Polyfills/AssertIgnoringLineEndings.php, src/Polyfills/AssertIgnoringLineEndings_Empty.php, src/TestCases/TestCasePHPUnitGte8.php, src/TestCases/TestCasePHPUnitLte7.php, src/TestCases/XTestCase.php, tests/Polyfills/AssertIgnoringLineEndingsTest.php, tests/TestCases/TestCaseTestTrait.php
PHPUnit 10.0.0 introduces the new `Assert::assertStringEqualsStringIgnoringLineEndings()` and `Assert::assertStringContainsStringIgnoringLineEndings()` methods.
This commit:
* An availability test and limited functional test for the functionality polyfilled.
Note: the function name for the `private` `normalizeLineEndings()` method is a little convoluted - `normalizeLineEndingsForIgnoringLineEndingsAssertions()`. This is intentional to prevent potential …
=> PHPUnit 10 | AssertIgnoringLineEndings trait: polyfill the Assert::assertStringEqualsStringIgnoringLineEndings() et al methods

README.md, phpunitpolyfills-autoload.php, src/Polyfills/AssertIsList.php, src/Polyfills/AssertIsList_Empty.php, src/TestCases/TestCasePHPUnitGte8.php, src/TestCases/TestCasePHPUnitLte7.php, src/TestCases/XTestCase.php, tests/Polyfills/AssertIsListTest.php, tests/TestCases/TestCaseTestTrait.php
PHPUnit 10.0.0 introduces the new `Assert::assertIsList()` method.
This commit:
* Functional tests for the functionality polyfilled.
Note: the methods use `static::` to call the PHPUnit native functionality. This allows for existing method overloads in a child class of the PHPUnit native `TestCase` to be respected.
Includes:
* Adding the new polyfill to the existing `TestCases` classes and adding a test for the polyfill availability to the …
=> PHPUnit 10 | AssertIsList trait: polyfill the Assert::assertIsList() method

.gitattributes, .github/workflows/test.yml, .gitignore, composer.json, phpunit10.xml.dist
The configuration file specification has undergone changes in PHPUnit 9.3 and 10.0.
Most notably:
* In PHPUnit 9.3, the manner of specifying the code coverage configuration has changed.
* In PHPUnit 10.0, a significant number of attributes of the `<phpunit>` element were removed or renamed.
While the `--migrate-configuration` command can upgrade a configuration for the changes in the format made in PHPUnit 9.3, some of the changes in the configuration format in PHPUnit 10 don't have one-on-one replacements and/or are not taken into account.
With that in mind, I deem it more appropriate to have a dedicated PHPUnit configuration file for PHPUnit 10 to ensure the test run will behave as intended.
This commit adds this dedicated configuration file for PHPUnit 10+.
Includes:
* Ignoring the new …
=> Tests: add separate configuration file for PHPUnit 10

tests/Polyfills/AssertFileEqualsSpecializationsTest.php, tests/Polyfills/AssertionRenamesTest.php, tests/TestCases/TestCaseTestTrait.php
... where appropriate.
This largely reverts commit 83ba7e30c0f479810a66d053db99b702e33f75ea.
=> Modernize: use constant scalar expressions

README.md, phpunitpolyfills-autoload.php, src/Polyfills/AssertObjectProperty.php, src/Polyfills/AssertObjectProperty_Empty.php, src/TestCases/TestCasePHPUnitGte8.php, src/TestCases/TestCasePHPUnitLte7.php, src/TestCases/XTestCase.php, tests/Polyfills/AssertObjectPropertyTest.php, tests/Polyfills/Fixtures/ObjectWithProperties.php, tests/TestCases/TestCaseTestTrait.php
PHPUnit 10.1.0 introduces the new `Assert::assertObjectHasProperty()` and `Assert::assertObjectNotHasProperty()` methods.
This commit:
* An availability test and functional tests for the functionality polyfilled.
Includes:
* Adding the new polyfill to the existing `TestCases` classes.
Refs:
* https://github.com/sebastianbergmann/phpunit/issues/5220
* https://github.com/sebastianbergmann/phpunit/pull/5231 (and follow up commits/PRs)
=> PHPUnit 10.1 | AssertObjectProperty trait: polyfill the Assert::assertObject[Not]HasProperty() methods

.github/workflows/markdown.yml, .remarkrc, README.md
The [`remark-lint-are-links-valid-alive`](https://github.com/wemake-services/remark-lint-are-links-valid) has been abandoned and doesn't allow to skip false positives.
The [`remark-lint-no-dead-urls`](https://github.com/remarkjs/remark-lint-no-dead-urls) plugin is still maintained and does allow adding some configuration to skip false positives.
This commit switches the one plugin out for the other.
=> RemarkLint: switch plugin + fix broken link

.github/workflows/test.yml, README.md, phpunit.xml.dist
This commit make the necessary changes to start recording and uploading code coverage data to Coveralls.
Includes:
* Updating the GH Actions `test` worflow to run (nearly) all non-experimental builds with code coverage and upload the results.
There is one exception: PHPUnit 8.x is not compatible with PHP 8.0+ for recording code coverage, so the PHP `8.0` with PHPUnit `8.x` build is exempt.
* Updating the PHPUnit config to show an inline code coverage summary.
* Adding a code coverage badge to the README.
Not included as already in place:
* Ignoring the potentially generated code coverage files in the `build/*` directory to prevent it being committed.
* Adding a script to the `composer.json` file to run code coverage.
Notes:
* Coverage will be recorded using `Xdebug` as the code coverage …
=> CI/QA: start recording code coverage

.remarkrc
Looks like the `remark-lint` project has released a new version fixing the bug causing the failing build earlier this week.
This commit reverts the rule change from PR #124.
Refs:
* https://github.com/remarkjs/remark-lint/releases/tag/9.1.2
* https://github.com/remarkjs/remark-lint/commit/639271aed95fa579623f385bade4939a9c70e959
=> GH Actions: tweaks for the markdown QA check

.github/workflows/test.yml, composer.json, phpunit10.xml.dist, tests/TestListeners/TestListenerTest.php
PHPUnit 10.0 has been released on Feb 3, 2023 and in the mean time PHPUnit 10.1 and 10.2 have also been released.
Refs:
* https://phpunit.de/announcements/phpunit-10.html
* https://github.com/sebastianbergmann/phpunit/blob/10.0.19/ChangeLog-10.0.md
* https://github.com/sebastianbergmann/phpunit/blob/10.1.3/ChangeLog-10.1.md
* https://github.com/sebastianbergmann/phpunit/blob/10.2/ChangeLog-10.2.md
The initial PHPUnit Polyfills 2.0.0 release will not contain a PHPUnit 10 compatible TestListener implementation.
This allows the tests to pass on PHPUnit 10 for now until that has been resolved.
Refs:
* https://github.com/Yoast/PHPUnit-Polyfills/issues/95#issuecomment-1577408987
* https://github.com/Yoast/PHPUnit-Polyfills/issues/128
As the PHPUnit Polyfills, as of now, will officially support …
=> Composer: allow PHPUnit 10.x + update CI to match

CHANGELOG.md, README.md, phpunitpolyfills-autoload.php
Includes:
* Adding a warning about the TestListener polyfill not (yet) being compatible with PHPUnit 10.
* Adding links to the documentation of some assertions, which are documented in the PHPUnit 10 documentation, but were previously undocumented.
* Updating all links to the PHPUnit documentation to point to the PHPUnit 10 docs instead of the PHPUnit 9 docs.
Includes minor punctuation fixes to older changelog entries.
=> Changelog and readme updates for the 2.0.0 release

.github/workflows/test.yml, README.md, phpunitpolyfills-autoload.php, src/Polyfills/AssertObjectProperty.php, src/Polyfills/AssertObjectProperty_Empty.php, src/TestCases/TestCasePHPUnitGte8.php, src/TestCases/TestCasePHPUnitLte7.php, src/TestCases/XTestCase.php, tests/Polyfills/AssertObjectPropertyTest.php, tests/Polyfills/Fixtures/ObjectWithProperties.php, tests/TestCases/TestCaseTestTrait.php
PHPUnit 10.1.0 introduced the new `Assert::assertObjectHasProperty()` and `Assert::assertObjectNotHasProperty()` methods.
These methods have now been backported to PHPUnit 9.6.11, so should be made available in the PHPUnit Polyfills 1.x series.
This commit:
* An availability test and functional tests for the functionality polyfilled.
Includes:
* Adding the new polyfill to the existing `TestCases` classes.
Refs:
* …
=> PHPUnit 9.6.11 | AssertObjectProperty trait: polyfill the Assert::assertObject[Not]HasProperty() methods

CHANGELOG.md, phpunitpolyfills-autoload.php
=> Changelog for the 1.1.0 release

.github/dependabot.yml
... as most updates are needed for both the 1.x, as well as the 2.x branch.
=> Dependabot: set target branch to 1.x

composer.json
Well, mostly (scripts are not alphabetized, but still grouped by task).
Note: this is done as a one-time only action. The normalize script will **_not_** be run in CI to enforce normalization.
Style has been standardized to `--indent-style=tab --indent-size=1`.
Ref: https://github.com/ergebnis/composer-normalize
These descriptions will be used when a list of the available scripts is requested on the command-line using the `composer list` or `composer run -l` commands.
These descriptions also help document the different scripts for the maintainers of the `composer.json` file.
Ref: https://getcomposer.org/doc/articles/scripts.md#custom-descriptions-
=> Composer: normalize the file + add script descriptions

.github/workflows/test.yml
The 2.x series supports PHPUnit 10. This no longer needs to be tested on the 1.x branch.
=> 1.x | GH Actions: remove the trial run against PHPUnit 10

.github/workflows/lint.yml, .github/workflows/test.yml
... which is expected later today.
Builds against PHP 8.3 should no longer be allowed to fail.
Includes adding an _allowed to fail_ build against PHP 8.4/dev.
=> GH Actions: update for release of PHP 8.3

.github/workflows/cs.yml, .github/workflows/lint.yml, .github/workflows/test.yml, .phpcs.xml.dist, composer.json, tests/bootstrap.php
YoastCS 3.0.0 has been released and is based on WordPressCS 3.0.0.
This commit makes the necessary updates for that:
* Composer: update the requirements.
* PHPCS ruleset:
- Exclude new WP specific rules which don't apply to this package.
- Exclude code modernization sniffs which can't be applied to this package yet.
- Enforce strict PSR-4 for both src and tests.
- Add a few selective exclusions for specific situations.
* GHA CS workflow: run the CS check on the latest PHP version.
No need to run on PHP 7.4 any more as the deprecations previously encountered were all fixed.
* Add one selective ignore annotation for a long closure (autoloader in the test bootstrap).
While YoastCS 3.0.0 contains lots of goodies, it also has a downside: a minimum PHP requirement of PHP 7.2, which conflicts …
=> Composer/PHPCS: update to YoastCS 3.0.0

.github/workflows/lint.yml, .phpcs.xml.dist, composer.json, tests/Polyfills/AssertObjectEqualsPHPUnitLt940Test.php, tests/Polyfills/AssertObjectEqualsTest.php, tests/Polyfills/Fixtures/ValueObject.php, tests/TestCases/TestCaseTestTrait.php
PHP 8.4 deprecates implicitly nullable parameters, i.e. typed parameter with a `null` default value, which are not explicitly declared as nullable.
The `ValueObject` fixture used in these tests used one such implicitly nullable parameters.
The tests for the `AssertObjectEquals` trait already needed two test classes to allow the method to be fully tests cross-version:
* One set which was run on PHPUnit < 9.4.0.
* One set which runs against PHP 7.0+.
As the nullability operator was introduced in PHP 7.1 and the particular test affected _does_ need to be typed to still test what it is supposed to test, I'm changing the requirements both test sets:
* The requirement for the first set of tests will now be PHPUnit < 9.4.0 AND PHP < 8.4.
* The requirement for the second set of test will now be …
=> Tests: tweaks to work round PHP 8.4 deprecation

.github/workflows/markdown.yml
The author of the `markdownlint-cli2` NPM package has published a GH Action runner for the package.
Advantages of switching to using that package:
* No need to monitor which Node version is supported by the NPM package, nor to manually update that. This is especially useful as the `markdownlint-cli2` doesn't use the GH release feature, which means that one can't subscribe to automatically get informed of releases (and the changelog of those).
Ref:
* https://github.com/marketplace/actions/markdownlint-cli2-action
=> GH Actions: update markdown lint workflow

src/Polyfills/AssertClosedResource.php
PHPUnit 8.5..38 and 9.6.19 contain a change in the PHAR files. In particular, a change in how external dependencies included in the packaged PHAR files are prefixed to prevent conflicts with potentially Composer installed dependencies on the same packages.
In practice, the prefix for these external dependencies which is being added when the PHAR is being build has changed from `PHPUnit\\` to `PHPUnitPHAR\\`.
This impacts the `AssertClosedResource` polyfill which uses the `SebastianBergmann\Exporter\Exporter` class from the external `Exporter` dependency.
This commit fixes the issue.
Refs:
* https://github.com/sebastianbergmann/phpunit/releases/tag/8.5.38
* https://github.com/sebastianbergmann/phpunit/releases/tag/9.6.19
=> AssertClosedResource: fix compatibility with PHPUnit 8/9 PHAR files

.github/workflows/test.yml
PHPUnit 8.5.38 and 9.6.19 contain a change in the PHAR build process, which means that classes external to PHPUnit are now prefixed differently, which breaks one polyfill.
As things were, such issues would previously not be caught by CI.
This commit adds a new job to the test workflow, which will run the tests against a range of PHP-PHPUnit combinations using the PHPUnit Phar to ensure any such issues will be automatically caught in the future.
The new test workflow will (very) selectively also upload code coverage to safeguard that the PHAR-file specific lines in the code base remain covered by tests as well.
=> GH Actions: run tests against PHPUnit PHAR files as well

CHANGELOG.md, phpunitpolyfills-autoload.php
=> Changelog for the 1.1.1 release

CHANGELOG.md, phpunitpolyfills-autoload.php
=> Changelog for the 2.0.1 release

.github/workflows/markdown.yml, .remarkrc, README.md
* Use Node 20 for the Remark check
* Make a tweak to the settings as RemarkLint is being awkward again.
* Fix up the tables to consistently have one space padding.
=> README/GH Actions: tweak markdown tables

.phpcs.xml.dist, composer.json, tests/Polyfills/AssertObjectEqualsTest.php, tests/Polyfills/Fixtures/ValueObject.php, tests/Polyfills/Fixtures/ValueObjectParamNotRequired.php, tests/TestCases/TestCaseTestTrait.php
Follow-up on PR #159.
This commit builds on the earlier change, but instead of making the whole `AssertObjectEqualsTest` class have a PHP 7.1 minimum requirement, it now limits that requirement to just the one affected test.
The affected test now uses a separate test fixture to allow the bulk of the tests to run on PHP 7.0 (which was the previous minimum requirement for these tests).
=> Tests: improve PHP 8.4 deprecation work-around

src/Helpers/ResourceHelper.php, src/Polyfills/AssertClosedResource.php, src/Polyfills/AssertFileDirectory.php, src/Polyfills/EqualToSpecializations.php
* Use unqualified class names in type references in documentation.
* Be specific about the class name.
* Have import `use` statements for all classes, even when only used in the docs.
* Remove outdated comment.
=> Docs: minor tweaks

.gitattributes, .github/workflows/cs.yml, .gitignore, phpstan.neon.dist
PHPStan is a good addition to the QA toolkit and with improvements PHPStan has made over the years is now a viable tool for us to use (previously it would give way too many false positives).
This commit:
* Adds a separate job to the `cs` workflow in GH Actions.
Notes:
- I've chosen **not** to add PHPStan to the Composer dependencies for two reasons:
1. It doesn't allow for installation on PHP < 7.2, which would break/block the `composer install` for the test runs.
2. It would potentially add dependencies which could conflict/cause problems for our test runs due to those defining token constants too.
_Note: this does not seem to be a problem with the latest versions anymore as the Composer package ships a PHAR file under the hood._
- We could potentially use [Phive](https://phar.io/) to …
=> CI/QA: add PHPStan

.gitattributes, phpstan-bootstrap.php, phpstan.neon.dist
Follow up on #175, but now for the 2.x branch.
As this branch uses some uncommon class names which PHPStan does not recognize by default, so tweaks are needed to get a passing build.
=> PHPStan: add bootstrap file

tests/Polyfills/ExpectPHPExceptionTest.php
PHP 8.4 deprecates passing `E_USER_ERROR` to `trigger_error()`, with the recommendation being to replace these type of calls with either an Exception or an `exit` statement.
As this is a test related to the PHPUnit `expectError()` assertion, the basic principle of the test cannot be changed without the test losing its validity.
Instead, this commit silences the PHP 8.4 deprecation notice specifically for PHP 8.4+.
Notes:
* The error silencing can not be added unconditionally as on PHP < 8.0, this would also silence the actual error, not just the deprecation notice.
* The commit also already adds a PHPUnit `@requires` annotation to indicate that the test should be skipped on PHP 9.0 as the deprecation will become an error in PHP 9.0. This `@requires` annotation with an operator is not …
=> PHP 8.4 | Silence deprecation notice in the tests

.github/workflows/lint.yml, .github/workflows/test.yml
The setup-php action runner offers the `nightly` alias for the PHP "dev" version. By using that alias instead of the hard-coded version number for PHP "next", the manual maintenance needed for the workflows is decreased and made less error-prone.
This also fixes the current "error" that the conditions for the "composer install" step still referenced PHP 8.3 instead of PHP 8.4.
There is a small down-side to this change. To explain this, we need to understand the PHP release cycle.
* Most years, a new PHP version is released towards end of November/beginning of December.
* However, the _branch_ for the new PHP minor/major is cut before the first RC, which - in the current release process - means towards end of September.
* From that moment onward, the "dev" version (`master` branch) of PHP …
=> GH Actions: use "nightly" instead of version nr for PHP-dev

.github/workflows/test.yml
The test run against PHPUnit `dev-main` was using the steps intended for PHPUnit < 10 instead of the steps for PHPUnit 10+, which it should be using.
=> GH Actions: fix test run against PHPUnit "dev"

.github/workflows/test.yml
PHPUnit 10 - at this time - can run on PHP 8.1/8.2/8.3 without version restrictions related to PHP compatibility issues.
=> GH Actions: remove some incorrect docs

.github/workflows/test.yml
As things were, each script contained four different steps which ran the unit test with different settings depending on certain conditions. Some of those conditions were also duplicated across steps to account for specific situations, which makes adjusting them and keeping the conditions stable and correct is fiddly.
This commit tries to simplify this and make it more robust by adding a new "Determine PHPUnit config" step, which sets certain variables depending on various conditions.
This allows to have only one test run step, which uses the variables to pass the correct command.
This should simplify maintenance when new PHPUnit versions need to be supported, as only the "Determine PHPUnit config" step should need updating and the other steps should not need changes.
=> GH Actions/tests: make conditions more robust

README.md
…without PHPUnit native replacement.
=> README: add expectDeprecation*() et al to FAQ > Removed functionality

.github/RELEASE-CHECKLIST.md, README.md, composer.json
The README for the 3.x version will be updated to reflect the features supported in the 3.x series.
This commit updates the README section about which versions of PHPUnit will be supported by which versions of the PHPUnit Polyfills.
As of now, the `main` branch, will be the release branch for PHPUnit Polyfills 3.x.
Includes minor textual tweaks to the release checklist.
=> 1.x  | Minor updates for start of 3.x branch

.github/workflows/test.yml
The 3.x series will support PHPUnit 11. This no longer needs to be tested on the 2.x branch.
=> 2.x | GH Actions: remove the trial run against PHPUnit 11

src/Polyfills/AssertIsList.php, tests/Polyfills/AssertIsListTest.php
PHPUnit 11.3.1 improved the type information in select assertion failure messages.
For the polyfills, this only affects the `AssertIsList` polyfill.
Now the choice was between the following:
* Just update the test(s) to have a different message expectation for PHPUnit 11.3.1+.
* Update the polyfills to mirror the improvement made in PHPUnit upstream.
I've chosen to implement the latter as it makes the message significantly more informative.
This means that on PHPUnit 6.x to 9.x and 11.3.1+, the new, improved message is shown. While on PHPUnit 10.0 - 11.3.0, the "old" message is shown as, in that case, the PHPUnit native `assertIsList()` method is used without the message improvements.
Includes:
* Renaming the `assertIsListFailureDescription()` method parameter from `$other` to `$value` to …
=> PHPUnit 11.3.1 | AssertIsList: sync error message with upstream

src/Polyfills/ExpectExceptionMessageMatches.php
PHPUnit 11.0 changed the visibility of a number of `TestCase` methods from `public` to `protected`, so the PHPUnit Polyfills should follow suit.
For the Polyfills, the only affected method is the polyfilled `expectExceptionMessageMatches()` method.
Refs:
* sebastianbergmann/phpunit#5213
* https://github.com/sebastianbergmann/phpunit/commit/8b8e38e962c1aa9b2a2497c00f66dc364f02092d
=> PHPUnit 11 | Make select methods `protected`

README.md, phpunitpolyfills-autoload.php, src/Polyfills/AssertArrayWithListKeys.php, src/Polyfills/AssertArrayWithListKeys_Empty.php, src/TestCases/TestCasePHPUnitGte8.php, src/TestCases/TestCasePHPUnitLte7.php, src/TestCases/XTestCase.php, tests/Polyfills/AssertArrayWithListKeysTest.php, tests/TestCases/TestCaseTestTrait.php
PHPUnit 11.0.0 introduces the new `Assert::assertArrayIsEqualToArrayOnlyConsideringListOfKeys()`, `Assert::assertArrayIsEqualToArrayIgnoringListOfKeys()`, `Assert::assertArrayIsIdenticalToArrayOnlyConsideringListOfKeys()` and `Assert::assertArrayIsIdenticalToArrayIgnoringListOfKeys()` methods.
This commit:
* An availability test and limited functional tests for the functionality polyfilled.
Includes:
* Adding the new polyfill to the existing `TestCases` …
=> PHPUnit 11 | AssertArrayWithListKeys trait: polyfill the Assert::assertArrayIsEqualToArrayOnlyConsideringListOfKeys() et al methods

README.md, phpunitpolyfills-autoload.php, src/Exceptions/InvalidComparisonMethodException.php, src/Helpers/ComparatorValidator.php, src/Polyfills/AssertObjectEquals.php, src/Polyfills/AssertObjectNotEquals.php, src/Polyfills/AssertObjectNotEquals_Empty.php, src/TestCases/TestCasePHPUnitGte8.php, src/TestCases/TestCasePHPUnitLte7.php, src/TestCases/XTestCase.php, tests/Polyfills/AssertObjectEqualsTest.php, tests/Polyfills/AssertObjectNotEqualsTest.php, tests/TestCases/TestCaseTestTrait.php
... as the same logic is needed for the (upcoming) PHPUnit 11.2+ `AssertObjectNotEquals` trait.
PHPUnit 11.2.0 introduced the new `Assert::assertObjectNotEquals()` method.
This commit:
* Adds two traits with the same name.
One to polyfill the method when not available in PHPUnit.
The other to allow for `use`-ing the trait in PHPUnit versions in which the method is already natively available.
* Adds tests.
As the polyfill contains logic to match the PHPUnit native implementation as closely as possible, while still being PHP and PHPUnit cross-version compatible, extensive unit tests have been added to ensure the behaviour of the polyfill matches that of the original function.
Includes: …
=> PHPUnit 11.2.0 | AssertObjectNotEquals trait: polyfill the Assert::assertObjectNotEquals() method

.github/workflows/test.yml, README.md, composer.json, phpstan.neon.dist, phpunit10.xml.dist, phpunitpolyfills-autoload.php, src/Polyfills/ExpectUserDeprecation.php, src/Polyfills/ExpectUserDeprecation_Empty.php, src/TestCases/TestCasePHPUnitGte8.php, src/TestCases/TestCasePHPUnitLte7.php, src/TestCases/XTestCase.php, tests/Polyfills/ExpectUserDeprecationTest.php, tests/TestCases/TestCaseTestTrait.php
PHPUnit 11.0.0 introduces the new `TestCase::expectUserDeprecationMessage()` and `TestCase::expectUserDeprecationMessageMatches()` methods.
These methods can largely be seen as replacements for the `TestCase::expectDeprecationMessage()` and `TestCase::expectDeprecationMessageMatches()` methods which were removed in PHPUnit 10.0, though there are significant differences between the implementation details of the old vs the new methods.
As PHPUnit 10 does not have any even semi-equivalent method(s) available, the challenge was to polyfill these methods for PHPUnit 10. And as these methods are expectation methods, not assertions, this is even more challenging as the information to evaluate a pass/fail is not available at the time of the method call, but only once the rest of the test code has …
=> PHPUnit 11 | ExpectUserDeprecationtrait: polyfill the TestCase::expectUserDeprecation*() methods

.github/RELEASE-CHECKLIST.md, CHANGELOG.md, README.md, phpunitpolyfills-autoload.php
Includes for the README:
* Updating the badge links
* Updating the warning about the TestListener polyfill not (yet) being compatible with PHPUnit 10/11.
* Removing the FAQ entry about `expectDeprecation*()` et al.
Includes minor release checklist update.
Closes #152
=> Changelog for the 3.0.0 release and other documentation updates

CHANGELOG.md, README.md
This partially reverts commit 0d2d6105602617d8bccd3b099a2489e254d734d8 (PR #206) after improvements upstream in the Remark no-dead-urls module.
Ref: remarkjs/remark-lint-no-dead-urls#54
=> Partially revert "README/Changelog: fix a few URLs which have changed"

.github/workflows/cs.yml
This Monday, [PHPStan 2.0 will be released](https://phpc.social/@OndrejMirtes/113441109253809720).
I've done some preliminary scans with PHPStan 2.0-dev to check if this would have an impact on this codebase and as things are, this would mean the build would start to fail.
For now, I'm proposing to make a small change in the GH Actions workflow to explicitly use PHPStan 1.x.
This buys us some time to evaluate PHPStan 2.0 properly and to make any changes needed to make the codebase compatible with PHPStan 2.x when we're ready for it.
=> GH Actions: use explicit PHPStan major

src/Polyfills/EqualToSpecializations.php
Follow up on #193
One more thing which can be cleaned up now support for PHPUnit < 6.4 has been dropped.
=> EqualToSpecializations: minor clean for drop of PHPUnit < 6.x

.github/workflows/cs.yml, phpstan.neon.dist
PHPStan 2.0 has been released :tada:
This commit updates the PHPStan configuration file for use with PHPStan 2.0 and switches the workflow to start using PHPStan 2.0.
Refs:
* https://phpstan.org/blog/phpstan-2-0-released-level-10-elephpants
* https://github.com/phpstan/phpstan/blob/2.0.x/UPGRADING.md
* https://github.com/phpstan/phpstan/releases/tag/2.0.0
=> PHPStan 2.0: update configuration

.phpcs.xml.dist, src/TestListeners/TestListenerSnakeCaseMethods.php, tests/TestListeners/Fixtures/TestListenerImplementation.php
Hmm... this is an awkward one and may need fixing in PHPCS 4.0, but in the mean time, let's fix it here.
The base `Yoast` ruleset includes select sniffs from the `WordPressVIPMinimum` ruleset. These sniff do not apply to the PHPUnit Polyfills package.
Now, when an `<exclude name="..."/>` rule references a ruleset name to _exclude_ those sniffs, that whole standard is read and included, after which the individual sniffs from the ruleset are excluded again.
This also means that if such a ruleset _also_ includes sniffs from other standards and/or customizations (changes in severity/excludes/messaging/properties etc) to sniffs from other standards, those sniffs from other standards will still be included and the customizations still be applied.
This will often silently lead to unexpected …
=> PHPCS: fix bug in ruleset

README.md
Also see: https://github.com/Yoast/PHPUnit-Polyfills/pull/225#pullrequestreview-2535048560
=> README: improve readability of table for `AssertIsType` trait

.github/pull_request_template.md, .remarkrc
Mostly as I have a tendency to forget to change the target branch to the oldest supported version for a PR when I haven't worked on this repo for a little while ... oops...
Let's hope this reminder will help prevent such snafus in the future.
Includes a tweak to the Remark config as the file name of the template needs to comply with the requirements by GitHub for such templates and this conflicts with the file name expectations set by Remark (by default).
Ref: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
=> Add pull request template

README.md, phpstan.neon.dist, phpunitpolyfills-autoload.php, src/Polyfills/AssertContainsOnly.php, src/Polyfills/AssertContainsOnly_Empty.php, src/TestCases/TestCasePHPUnitGte8.php, src/TestCases/TestCasePHPUnitLte7.php, src/TestCases/XTestCase.php, tests/Polyfills/AssertContainsOnlyTest.php, tests/TestCases/TestCaseTestTrait.php
PHPUnit 11.5.0 introduced a range of new assertions. These assertions are specialized alternatives to the pre-existing `assert[Not]ContainsOnly()` methods, which are now soft deprecated and will be removed in PHPUnit 13.0.
This commit:
* Adds two traits with the same name.
One to polyfill the methods when not available in PHPUnit.
The other to allow for `use`-ing the trait in PHPUnit versions in which the methods are already natively available.
* Adds logic to the custom autoloader which will load the correct trait depending on the PHPUnit version used.
* Adds tests.
Most polyfilled methods can just fall-through to the pre-existing methods as a polyfill.
The exceptions to this rule are:
* `assertContains[Not]OnlyIterable()` which needs custom logic for PHPUnit < 7.1.0 in which the PHP …
=> PHPUnit 11.5.0 | AssertContainsOnly trait: polyfill the Assert::assertContains[Not]Only*() methods

.remarkrc
... as Remark seems to be struggling with it and we don't have influence on the potentially broken HTML created by GH anyway, so we can't fix the anchor on the page. The link works, so it really is a non-issue and the failing CI builds are getting annoying.
=> Remark: ignore a particular anchor link

.phpcs.xml.dist
These haven't been necessary since support for PHP < 7.0 was dropped in PR #192.
=> PHPCS: minor ruleset clean up

.github/workflows/lint.yml, composer.json
The `lint-gte84` script became a duplicate of the `lint-gte80` script with the version drop of PHP < 7.0 in PR #192, so let's remove this duplication.
=> Composer/lint: remove redundant duplicate script

src/Polyfills/AssertContainsOnly.php
This could be problematic when tests use function calls with named parameters, so let's make sure the parameter name matches the one used in PHPUnit.
=> AssertContainsOnly::assertContainsNotOnlyInstancesOf(): fix incorrect param name

.phpcs.xml.dist, phpunitpolyfills-autoload.php, tests/Polyfills/AssertFileEqualsSpecializationsTest.php, tests/Polyfills/AssertObjectEqualsTest.php, tests/Polyfills/AssertObjectNotEqualsTest.php, tests/Polyfills/AssertionRenamesTest.php
... as supported by PHP since PHP 7.1.
Note: the `AssertFileEqualsSpecializationsTest::PATH_TO_EXPECTED` constant is declared as `public` as it is also used by tests in the `TestCaseTestTrait`.
=> Modernize: add visibility for class constants

.phpcs.xml.dist, phpstan-bootstrap.php, phpstan.neon.dist, phpunitpolyfills-autoload.php, src/Exceptions/InvalidComparisonMethodException.php, src/Helpers/ComparatorValidator.php, src/Helpers/ResourceHelper.php, src/Polyfills/AssertArrayWithListKeys.php, src/Polyfills/AssertClosedResource.php, src/Polyfills/AssertContainsOnly.php, src/Polyfills/AssertFileEqualsSpecializations.php, src/Polyfills/AssertIgnoringLineEndings.php, src/Polyfills/AssertIsList.php, src/Polyfills/AssertObjectEquals.php, src/Polyfills/AssertObjectNotEquals.php, src/Polyfills/AssertObjectProperty.php, src/Polyfills/AssertionRenames.php, src/Polyfills/EqualToSpecializations.php, src/Polyfills/ExpectExceptionMessageMatches.php, src/Polyfills/ExpectUserDeprecation.php, src/TestListeners/TestListenerSnakeCaseMethods.php, tests/Polyfills/AssertIgnoringLineEndingsTest.php, tests/Polyfills/AssertObjectEqualsTest.php, tests/Polyfills/AssertObjectNotEqualsTest.php, tests/bootstrap.php
In line with the new minimum of PHPUnit 7.x, the assertions in the PHPUnit Polyfills will now have both parameter as well as return type declarations (wherever possible considering the minimum supported PHP version of PHP 7.1).
Additional type declarations will be added in future majors if/when the minimum supported PHP version allows for it.
Includes removing polyfilled inline type checks for assertions which were introduced in PHPUnit with declared types, but for which the polyfills couldn't type the parameters prior to this.
Includes minor adjustments to exception expectations in the tests to allow for the PHP native `TypeError`s - in contrast to the emulated ones.
Notes:
* `AssertObjectProperty`: the `string` type for the `$propertyName` parameter for the …
=> Modernize: add scalar + return type declarations (wherever possible)

phpstan.neon.dist
New PHPStan release, new issue with the ignores.
Fixed now in a way that should be more stable.
=> PHPStan: fix ignores

.github/dependabot.yml
Composer checks have started to run into trouble with the minimum PHP version vs the YoastCS dependency (which has a higher minimum PHP version).
As Dependabot has never made a useful contribution for the Composer dependencies anyway AND there are only a few dependencies, we may as well drop it to get rid of the incessant error notifications.
Ref: https://github.com/Yoast/PHPUnit-Polyfills/network/updates/958266171
=> Dependabot: remove Composer ecosystem

.github/workflows/test.yml
The 4.x series will support PHPUnit 12. This no longer needs to be tested on the 3.x branch.
=> 3.x | GH Actions: remove the trial run against PHPUnit 12

.github/RELEASE-CHECKLIST.md, README.md, composer.json
The README for the 4.x version will be updated to reflect the features supported in the 4.x series.
This commit updates the README section about which versions of PHPUnit will be supported by which versions of the PHPUnit Polyfills.
As of now, the `main` branch, will be the release branch for PHPUnit Polyfills 4.x.
Includes minor textual tweaks to the release checklist.
=> 1.x | Minor updates for 4.x branch

.github/workflows/cs.yml, .github/workflows/lint.yml, .github/workflows/test.yml
Follow up on #244.
This adds the `GITHUB_TOKEN` to get round the rate limiting where necessary.
It also adds `fail-fast` to get `setup-php` to exit with a non-zero exit code if something required in `tools` could not be installed (or other customizations failed). This prevents running unnecessary interim steps if a later step would never be able to succeed anyway.
=> GH Actions: prevent more rate limiting issues

CHANGELOG.md, phpunitpolyfills-autoload.php
=> Changelog for the 3.1.2 release

CHANGELOG.md, README.md, phpunitpolyfills-autoload.php
Includes for the README:
* Updating the badge links
* Updating the warning about the TestListener polyfill not (yet) being compatible with PHPUnit 10/11/12.
=> Changelog for the 4.0.0 release and other documentation updates
