.github/workflows/test.yml
... to test against the highest and a "low" PHPUnit version for each supported PHP version.
=> GH Actions: expand the test matrix

.phpcs.xml.dist, src/Polyfills/AssertObjectEquals.php, tests/Polyfills/AssertObjectEqualsPHPUnitLt940Test.php, tests/Polyfills/AssertObjectEqualsTest.php, tests/Polyfills/Fixtures/ValueObject.php, tests/Polyfills/Fixtures/ValueObjectNoReturnType.php
... and add tests covering this exception.
=> AssertObjectEquals: improve "not boolean return value" error message

.github/RELEASE-CHECKLIST.md
... to document the tasks which should be completed for every release.
Follow up on #46 and #47
=> Add a release checklist

CHANGELOG.md, phpunitpolyfills-autoload.php
=> Changelog for the 1.0.2 release

.github/workflows/cs.yml, .github/workflows/lint.yml, .github/workflows/test.yml, CHANGELOG.md, README.md, phpunitpolyfills-autoload.php, src/Polyfills/AssertClosedResource.php, tests/Polyfills/AssertClosedResourceTestCase.php, tests/TestListeners/Fixtures/FailurePHPUnitGte7.php, tests/TestListeners/Fixtures/IncompletePHPUnitGte7.php, tests/TestListeners/Fixtures/RiskyPHPUnitGte7.php, tests/TestListeners/Fixtures/SkippedPHPUnitGte7.php, tests/TestListeners/Fixtures/SuccessPHPUnitGte7.php, tests/TestListeners/Fixtures/TestErrorPHPUnitGte7.php, tests/TestListeners/Fixtures/WarningPHPUnitGte7.php, tests/TestListeners/TestListenerTest.php, tests/bootstrap.php
=> Release version 1.0.3

tests/Polyfills/AssertFileDirectoryTest.php
Update some `@requires` tags now PHPUnit 10.0 has been released.
=> Tests: minor update for release of PHPUnit 10.0.0

.github/workflows/test.yml, CHANGELOG.md, phpunitpolyfills-autoload.php
Includes minor documentation addition in CI test workflow.
=> Changelog for the 1.0.5 release

.github/workflows/lint.yml
.. via the `cs2pr` tool.
Ref:
* https://github.com/staabm/annotate-pull-request-from-checkstyle
=> GH Actions: show linting errors in PRs

tests/Polyfills/AssertIgnoringLineEndingsTest.php
... to cover handling of custom error messages.
=> AssertIgnoringLineEndings: add extra test

tests/Polyfills/AssertIgnoringLineEndingsTest.php, tests/Polyfills/AssertStringContainsTest.php
... which was causing test failures.
=> Tests: account for changes failure message format

.github/workflows/cs.yml, .github/workflows/lint.yml, .github/workflows/test.yml, .markdownlint-cli2.yaml
... as the old URLs are no longer valid.
.... which should be helpful for debugging if needed.
=> Various minor CI tweaks

src/Polyfills/AssertObjectProperty.php, tests/Polyfills/AssertObjectPropertyTest.php
(artifact from the backport from the 2.x branch)
=> CS/QA: remove unused import use statements (1.x branch only)

src/Polyfills/ExpectException.php, src/TestListeners/TestListenerDefaultImplementationPHPUnit6.php, src/TestListeners/TestListenerDefaultImplementationPHPUnitGte7.php, src/TestListeners/TestListenerDefaultImplementationPHPUnitLte5.php, src/TestListeners/TestListenerSnakeCaseMethods.php, tests/Polyfills/AssertClosedResourceNotResourceTest.php, tests/Polyfills/AssertClosedResourceShmopTest.php, tests/Polyfills/AssertFileDirectoryTest.php, tests/Polyfills/AssertObjectPropertyTest.php, tests/Polyfills/AssertStringContainsTest.php, tests/Polyfills/ExpectExceptionTest.php, tests/TestCases/TestCaseTestTrait.php, tests/TestListeners/Fixtures/TestListenerImplementation.php
=> Docs: various improvements

.github/workflows/test.yml
=> GH Actions/test: also test against PHPUnit 10/PHP 8.4

composer.json
... for dev dependencies.
Refs:
* https://github.com/php-parallel-lint/PHP-Parallel-Lint/releases/tag/v1.4.0
* https://github.com/Yoast/YoastCS/releases/tag/3.1.0
=> Composer: update version constraints

tests/README.md
... to better reflect the current reality.
=> Tests README: textual update

.github/RELEASE-CHECKLIST.md
* Add checklist item about how to handle the `main` branch.
=> Release checkist: minor update

CHANGELOG.md, phpunitpolyfills-autoload.php
=> Changelog for the 1.1.2 release

CHANGELOG.md, phpunitpolyfills-autoload.php
=> Changelog for the 2.0.2 release

CHANGELOG.md, README.md
Fix a few URLs which were being redirected.
Includes:
* Replacing badges from poser.pugx.org with badges using img.shields.io.
=> README/Changelog: fix a few URLs which have changed

phpstan.neon.dist
... due to changes in PHPStan itself.
=> PHPStan: minor config tweak

README.md
Also see: https://github.com/Yoast/PHPUnit-Polyfills/pull/225#pullrequestreview-2535048560
=> README: improve readability of table for `AssertIsType` trait

CHANGELOG.md, phpunitpolyfills-autoload.php
=> Changelog for the 1.1.3 release

CHANGELOG.md, phpunitpolyfills-autoload.php
=> Changelog for the 2.0.3 release

CHANGELOG.md, phpunitpolyfills-autoload.php
=> Changelog for the 3.1.0 release

CHANGELOG.md, phpunitpolyfills-autoload.php
=> Changelog for the 3.1.1 release

CHANGELOG.md, phpunitpolyfills-autoload.php
=> Changelog for the 1.1.4 release

CHANGELOG.md, phpunitpolyfills-autoload.php
=> Changelog for the 2.0.4 release
